export const categories = [
  { id: 1, name: 'Electronics', slug: 'electronics', description: 'Latest gadgets and tech accessories.', icon: 'Smartphone', image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&h=400&fit=crop&q=80', productCount: 7 },
  { id: 2, name: 'Fashion', slug: 'fashion', description: 'Trendy clothing and accessories for all seasons.', icon: 'Shirt', image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&h=400&fit=crop&q=80', productCount: 6 },
  { id: 3, name: 'Home & Living', slug: 'home-living', description: 'Elegant decor and smart home solutions.', icon: 'Home', image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&h=400&fit=crop&q=80', productCount: 5 },
  { id: 4, name: 'Beauty', slug: 'beauty', description: 'Premium cosmetics and personal care items.', icon: 'Sparkles', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=400&fit=crop&q=80', productCount: 5 },
  { id: 5, name: 'Sports', slug: 'sports', description: 'High-quality fitness and outdoor gear.', icon: 'Dumbbell', image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop&q=80', productCount: 5 },
  { id: 6, name: 'Books', slug: 'books', description: 'Bestsellers, guides, and educational reads.', icon: 'BookOpen', image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=400&fit=crop&q=80', productCount: 5 },
  { id: 7, name: 'Toys & Games', slug: 'toys-games', description: 'Fun and educational items for kids and families.', icon: 'Gamepad2', image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&h=400&fit=crop&q=80', productCount: 4 },
  { id: 8, name: 'Groceries', slug: 'groceries', description: 'Gourmet foods and essential pantry items.', icon: 'ShoppingBasket', image: 'https://images.unsplash.com/photo-1543168256-418811576931?w=600&h=400&fit=crop&q=80', productCount: 5 }
];

export const products = [
  // ELECTRONICS (7)
  {
    id: 1,
    name: 'Wireless Headphones',
    description: 'Experience premium sound quality with these active noise-canceling wireless headphones. Comfortable over-ear design with 30-hour battery life.',
    price: 79.99,
    originalPrice: 129.99,
    discount: 38,
    images: ['https://picsum.photos/seed/wireless-headphones-1/500/500', 'https://picsum.photos/seed/wireless-headphones-2/500/500', 'https://picsum.photos/seed/wireless-headphones-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'SoundCore',
    rating: 4.8,
    reviewCount: 320,
    stock: 45,
    tags: ['featured', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: ['Black', 'Silver', 'Navy'],
    sizes: null,
    features: ['Active Noise Cancellation', '30-Hour Battery Life', 'Bluetooth 5.0', 'Built-in Microphone'],
    createdAt: '2024-01-10T00:00:00Z'
  },
  {
    id: 2,
    name: 'Smart Watch Pro',
    description: 'Track your fitness, receive notifications, and monitor your health with this advanced smartwatch. Water-resistant up to 50 meters.',
    price: 199.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/smart-watch-pro-1/500/500', 'https://picsum.photos/seed/smart-watch-pro-2/500/500', 'https://picsum.photos/seed/smart-watch-pro-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'TechPro',
    rating: 4.6,
    reviewCount: 215,
    stock: 120,
    tags: ['new', 'trending'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Space Gray', 'Rose Gold', 'Midnight'],
    sizes: ['40mm', '44mm'],
    features: ['Heart Rate Monitor', 'GPS Tracking', 'Water Resistant (50m)', 'Always-On Display'],
    createdAt: '2024-02-15T00:00:00Z'
  },
  {
    id: 3,
    name: '4K Drone Camera',
    description: 'Capture stunning aerial photography and video with this lightweight, easy-to-fly drone. Features intelligent flight modes and 3-axis gimbal.',
    price: 449.00,
    originalPrice: 499.00,
    discount: 10,
    images: ['https://picsum.photos/seed/4k-drone-camera-1/500/500', 'https://picsum.photos/seed/4k-drone-camera-2/500/500', 'https://picsum.photos/seed/4k-drone-camera-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'AeroVue',
    rating: 4.9,
    reviewCount: 85,
    stock: 15,
    tags: ['premium', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['White'],
    sizes: null,
    features: ['4K Video Resolution', '3-Axis Gimbal Stabilization', 'Intelligent Flight Modes', '31-Min Flight Time'],
    createdAt: '2024-01-20T00:00:00Z'
  },
  {
    id: 4,
    name: 'Bluetooth Speaker',
    description: 'Portable and rugged Bluetooth speaker with incredible bass and 360-degree sound. IP67 waterproof rating makes it perfect for outdoors.',
    price: 59.99,
    originalPrice: 89.99,
    discount: 33,
    images: ['https://picsum.photos/seed/bluetooth-speaker-1/500/500', 'https://picsum.photos/seed/bluetooth-speaker-2/500/500', 'https://picsum.photos/seed/bluetooth-speaker-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'SoundCore',
    rating: 4.5,
    reviewCount: 410,
    stock: 200,
    tags: ['sale'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: ['Black', 'Blue', 'Red'],
    sizes: null,
    features: ['IP67 Waterproof', '360° Sound', '15-Hour Playtime', 'Built-in Powerbank'],
    createdAt: '2024-03-05T00:00:00Z'
  },
  {
    id: 5,
    name: 'Gaming Keyboard',
    description: 'Mechanical gaming keyboard with customizable RGB backlighting and responsive switches. Designed for competitive gaming and typing comfort.',
    price: 129.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/gaming-keyboard-1/500/500', 'https://picsum.photos/seed/gaming-keyboard-2/500/500', 'https://picsum.photos/seed/gaming-keyboard-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'TechPro',
    rating: 4.7,
    reviewCount: 150,
    stock: 30,
    tags: ['gaming', 'featured'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Black', 'White'],
    sizes: null,
    features: ['Mechanical Switches', 'RGB Backlighting', 'Programmable Macros', 'Detachable Wrist Rest'],
    createdAt: '2024-04-01T00:00:00Z'
  },
  {
    id: 6,
    name: 'Portable Monitor',
    description: 'Ultra-slim 15.6-inch portable monitor with 1080p resolution. Easily connects to laptops, smartphones, and gaming consoles via USB-C or HDMI.',
    price: 189.99,
    originalPrice: 229.99,
    discount: 17,
    images: ['https://picsum.photos/seed/portable-monitor-1/500/500', 'https://picsum.photos/seed/portable-monitor-2/500/500', 'https://picsum.photos/seed/portable-monitor-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'VisionTech',
    rating: 4.4,
    reviewCount: 95,
    stock: 0,
    tags: ['accessories'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Dark Gray'],
    sizes: null,
    features: ['15.6" IPS Display', '1080p Resolution', 'USB-C and Mini-HDMI Ports', 'Ultra-Slim Design'],
    createdAt: '2024-02-10T00:00:00Z'
  },
  {
    id: 7,
    name: 'Noise Cancelling Earbuds',
    description: 'True wireless earbuds with adaptive noise cancellation and immersive spatial audio. Comes with a wireless charging case for convenience.',
    price: 149.99,
    originalPrice: 179.99,
    discount: 16,
    images: ['https://picsum.photos/seed/noise-cancelling-earbuds-1/500/500', 'https://picsum.photos/seed/noise-cancelling-earbuds-2/500/500', 'https://picsum.photos/seed/noise-cancelling-earbuds-3/500/500'],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'SoundCore',
    rating: 4.8,
    reviewCount: 280,
    stock: 60,
    tags: ['bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['White', 'Black'],
    sizes: null,
    features: ['Adaptive Noise Cancellation', 'Spatial Audio', 'Wireless Charging Case', '24-Hour Battery Life (with case)'],
    createdAt: '2024-03-15T00:00:00Z'
  },

  // FASHION (6)
  {
    id: 8,
    name: 'Classic Leather Jacket',
    description: 'Timeless genuine leather jacket with a modern fit. Features durable hardware and a comfortable lining for year-round wear.',
    price: 249.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/classic-leather-jacket-1/500/500', 'https://picsum.photos/seed/classic-leather-jacket-2/500/500', 'https://picsum.photos/seed/classic-leather-jacket-3/500/500'],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'NovaStyle',
    rating: 4.7,
    reviewCount: 112,
    stock: 25,
    tags: ['premium', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Black', 'Brown'],
    sizes: ['S', 'M', 'L', 'XL'],
    features: ['Genuine Leather', 'Modern Fit', 'Durable YKK Zippers', 'Polyester Lining'],
    createdAt: '2024-01-05T00:00:00Z'
  },
  {
    id: 9,
    name: 'Running Sneakers Pro',
    description: 'Lightweight and breathable running shoes designed for ultimate comfort and performance. Features advanced cushioning technology.',
    price: 119.99,
    originalPrice: 149.99,
    discount: 20,
    images: ['https://picsum.photos/seed/running-sneakers-pro-1/500/500', 'https://picsum.photos/seed/running-sneakers-pro-2/500/500', 'https://picsum.photos/seed/running-sneakers-pro-3/500/500'],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'NovaSport',
    rating: 4.9,
    reviewCount: 340,
    stock: 80,
    tags: ['bestseller'],
    isNew: true,
    isBestSeller: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: ['White/Blue', 'Black/Red', 'Gray'],
    sizes: ['8', '9', '10', '11', '12'],
    features: ['Advanced Cushioning', 'Breathable Mesh Upper', 'Lightweight Design', 'Durable Rubber Outsole'],
    createdAt: '2024-04-10T00:00:00Z'
  },
  {
    id: 10,
    name: 'Designer Sunglasses',
    description: 'Chic and stylish designer sunglasses with polarized lenses. Offers 100% UV protection and a comfortable, lightweight frame.',
    price: 89.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/designer-sunglasses-1/500/500', 'https://picsum.photos/seed/designer-sunglasses-2/500/500', 'https://picsum.photos/seed/designer-sunglasses-3/500/500'],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'Lumina',
    rating: 4.5,
    reviewCount: 65,
    stock: 40,
    tags: ['accessories'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Tortoise', 'Black', 'Gold'],
    sizes: null,
    features: ['Polarized Lenses', '100% UV Protection', 'Lightweight Acetate Frame', 'Includes Hard Case'],
    createdAt: '2024-02-20T00:00:00Z'
  },
  {
    id: 11,
    name: 'Silk Evening Dress',
    description: 'Elegant floor-length evening dress made from luxurious pure silk. Perfect for galas, weddings, and special occasions.',
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    images: ['https://picsum.photos/seed/silk-evening-dress-1/500/500', 'https://picsum.photos/seed/silk-evening-dress-2/500/500', 'https://picsum.photos/seed/silk-evening-dress-3/500/500'],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'Elegance',
    rating: 4.8,
    reviewCount: 42,
    stock: 12,
    tags: ['premium', 'featured'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Emerald Green', 'Midnight Blue', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L'],
    features: ['100% Pure Silk', 'Floor-Length', 'Concealed Zipper', 'Dry Clean Only'],
    createdAt: '2024-03-25T00:00:00Z'
  },
  {
    id: 12,
    name: 'Cashmere Sweater',
    description: 'Incredibly soft and warm cashmere sweater with a classic crew neck. A versatile wardrobe essential for colder days.',
    price: 159.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/cashmere-sweater-1/500/500', 'https://picsum.photos/seed/cashmere-sweater-2/500/500', 'https://picsum.photos/seed/cashmere-sweater-3/500/500'],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'NovaStyle',
    rating: 4.6,
    reviewCount: 180,
    stock: 55,
    tags: ['winter', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Camel', 'Charcoal', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    features: ['100% Mongolian Cashmere', 'Crew Neck', 'Ribbed Cuffs and Hem', 'Ultra-Soft Feel'],
    createdAt: '2024-01-12T00:00:00Z'
  },
  {
    id: 13,
    name: 'Canvas Backpack',
    description: 'Durable and spacious canvas backpack perfect for daily commutes or weekend trips. Includes a padded laptop sleeve and multiple pockets.',
    price: 49.99,
    originalPrice: 69.99,
    discount: 28,
    images: ['https://picsum.photos/seed/canvas-backpack-1/500/500', 'https://picsum.photos/seed/canvas-backpack-2/500/500', 'https://picsum.photos/seed/canvas-backpack-3/500/500'],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'UrbanGear',
    rating: 4.4,
    reviewCount: 225,
    stock: 0,
    tags: ['accessories', 'sale'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Olive', 'Black', 'Khaki'],
    sizes: null,
    features: ['Durable Cotton Canvas', 'Padded 15" Laptop Sleeve', 'Water-Resistant Coating', 'Ergonomic Straps'],
    createdAt: '2024-02-28T00:00:00Z'
  },

  // HOME & LIVING (5)
  {
    id: 14,
    name: 'Smart LED Floor Lamp',
    description: 'Modern minimalist floor lamp with customizable RGB lighting. Controllable via smartphone app or voice assistants like Alexa and Google Home.',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    images: ['https://picsum.photos/seed/smart-led-floor-lamp-1/500/500', 'https://picsum.photos/seed/smart-led-floor-lamp-2/500/500', 'https://picsum.photos/seed/smart-led-floor-lamp-3/500/500'],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'Lumina',
    rating: 4.7,
    reviewCount: 156,
    stock: 40,
    tags: ['smart-home', 'featured'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: ['Black', 'White'],
    sizes: null,
    features: ['16 Million Colors', 'App Control', 'Voice Assistant Compatible', 'Dimmable'],
    createdAt: '2024-03-10T00:00:00Z'
  },
  {
    id: 15,
    name: 'Ergonomic Office Chair',
    description: 'Fully adjustable ergonomic chair designed for all-day comfort. Features lumbar support, breathable mesh back, and padded armrests.',
    price: 249.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/ergonomic-office-chair-1/500/500', 'https://picsum.photos/seed/ergonomic-office-chair-2/500/500', 'https://picsum.photos/seed/ergonomic-office-chair-3/500/500'],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'WorkWell',
    rating: 4.8,
    reviewCount: 310,
    stock: 20,
    tags: ['furniture', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Black', 'Gray'],
    sizes: null,
    features: ['Adjustable Lumbar Support', 'Breathable Mesh', '3D Armrests', 'Tilt Mechanism'],
    createdAt: '2024-01-25T00:00:00Z'
  },
  {
    id: 16,
    name: 'Luxury Throw Blanket',
    description: 'Ultra-soft faux fur throw blanket that adds elegance and warmth to any room. Generously sized and machine washable for easy care.',
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    images: ['https://picsum.photos/seed/luxury-throw-blanket-1/500/500', 'https://picsum.photos/seed/luxury-throw-blanket-2/500/500', 'https://picsum.photos/seed/luxury-throw-blanket-3/500/500'],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'CozyHome',
    rating: 4.9,
    reviewCount: 420,
    stock: 85,
    tags: ['decor'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Ivory', 'Taupe', 'Charcoal'],
    sizes: ['50" x 60"', '60" x 80"'],
    features: ['Premium Faux Fur', 'Machine Washable', 'Reversible Design', 'Ultra-Soft'],
    createdAt: '2024-02-05T00:00:00Z'
  },
  {
    id: 17,
    name: 'Ceramic Vase Set',
    description: 'Set of 3 modern ceramic vases with a matte finish. Perfect for displaying dried flowers or as standalone decorative pieces.',
    price: 45.00,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/ceramic-vase-set-1/500/500', 'https://picsum.photos/seed/ceramic-vase-set-2/500/500', 'https://picsum.photos/seed/ceramic-vase-set-3/500/500'],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'Artisan Decor',
    rating: 4.5,
    reviewCount: 78,
    stock: 35,
    tags: ['decor'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Terracotta', 'White', 'Black'],
    sizes: null,
    features: ['Set of 3 Vases', 'Matte Finish', 'Handcrafted Ceramic', 'Minimalist Design'],
    createdAt: '2024-04-05T00:00:00Z'
  },
  {
    id: 18,
    name: 'Robot Vacuum Cleaner',
    description: 'Intelligent robot vacuum with mapping technology and strong suction. Automatically returns to the charging dock when low on battery.',
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    images: ['https://picsum.photos/seed/robot-vacuum-cleaner-1/500/500', 'https://picsum.photos/seed/robot-vacuum-cleaner-2/500/500', 'https://picsum.photos/seed/robot-vacuum-cleaner-3/500/500'],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'CleanBot',
    rating: 4.6,
    reviewCount: 215,
    stock: 15,
    tags: ['smart-home', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Black', 'White'],
    sizes: null,
    features: ['Smart Mapping', '2000Pa Suction Power', 'Self-Charging', 'App & Voice Control'],
    createdAt: '2024-01-18T00:00:00Z'
  },

  // BEAUTY (5)
  {
    id: 19,
    name: 'Luxury Skincare Set',
    description: 'Complete daily skincare routine including cleanser, toner, serum, and moisturizer. Formulated with natural ingredients for radiant skin.',
    price: 125.00,
    originalPrice: 150.00,
    discount: 16,
    images: ['https://picsum.photos/seed/luxury-skincare-set-1/500/500', 'https://picsum.photos/seed/luxury-skincare-set-2/500/500', 'https://picsum.photos/seed/luxury-skincare-set-3/500/500'],
    category: 'Beauty',
    categorySlug: 'beauty',
    brand: 'GlowNaturals',
    rating: 4.9,
    reviewCount: 380,
    stock: 50,
    tags: ['premium', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['4-Step Routine', 'Natural Ingredients', 'Cruelty-Free', 'Suitable for All Skin Types'],
    createdAt: '2024-02-12T00:00:00Z'
  },
  {
    id: 20,
    name: 'Premium Perfume Collection',
    description: 'A discovery set of 5 signature fragrances. From floral to woody notes, find your perfect scent for any occasion.',
    price: 85.00,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/premium-perfume-collection-1/500/500', 'https://picsum.photos/seed/premium-perfume-collection-2/500/500', 'https://picsum.photos/seed/premium-perfume-collection-3/500/500'],
    category: 'Beauty',
    categorySlug: 'beauty',
    brand: 'AromaEssence',
    rating: 4.7,
    reviewCount: 145,
    stock: 30,
    tags: ['gift'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['5 x 10ml Bottles', 'Long-lasting Scent', 'Travel Friendly', 'Elegant Packaging'],
    createdAt: '2024-04-02T00:00:00Z'
  },
  {
    id: 21,
    name: 'Organic Hair Care Kit',
    description: 'Revitalizing shampoo and conditioner duo enriched with argan oil and keratin. Restores shine and strength to damaged hair.',
    price: 45.00,
    originalPrice: 60.00,
    discount: 25,
    images: ['https://picsum.photos/seed/organic-hair-care-kit-1/500/500', 'https://picsum.photos/seed/organic-hair-care-kit-2/500/500', 'https://picsum.photos/seed/organic-hair-care-kit-3/500/500'],
    category: 'Beauty',
    categorySlug: 'beauty',
    brand: 'PureStrands',
    rating: 4.5,
    reviewCount: 210,
    stock: 65,
    tags: ['organic', 'sale'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: null,
    sizes: null,
    features: ['Sulfate-Free', 'Contains Argan Oil & Keratin', 'Color Safe', 'Vegan'],
    createdAt: '2024-01-30T00:00:00Z'
  },
  {
    id: 22,
    name: 'LED Makeup Mirror',
    description: 'Tri-fold vanity mirror with adjustable LED lighting and 3X/2X/1X magnification panels. Perfect for flawless makeup application.',
    price: 34.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/led-makeup-mirror-1/500/500', 'https://picsum.photos/seed/led-makeup-mirror-2/500/500', 'https://picsum.photos/seed/led-makeup-mirror-3/500/500'],
    category: 'Beauty',
    categorySlug: 'beauty',
    brand: 'GlamTech',
    rating: 4.6,
    reviewCount: 520,
    stock: 120,
    tags: ['accessories', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['White', 'Rose Gold', 'Black'],
    sizes: null,
    features: ['Adjustable Brightness', '3 Magnification Modes', '180° Rotation', 'Dual Power Supply (USB/Battery)'],
    createdAt: '2024-02-22T00:00:00Z'
  },
  {
    id: 23,
    name: 'Essential Oil Diffuser',
    description: 'Ultrasonic aromatherapy diffuser with a beautiful wood grain finish and 7 color-changing LED lights. Includes auto shut-off feature.',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    images: ['https://picsum.photos/seed/essential-oil-diffuser-1/500/500', 'https://picsum.photos/seed/essential-oil-diffuser-2/500/500', 'https://picsum.photos/seed/essential-oil-diffuser-3/500/500'],
    category: 'Beauty',
    categorySlug: 'beauty',
    brand: 'ZenAura',
    rating: 4.8,
    reviewCount: 315,
    stock: 0,
    tags: ['wellness'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Light Wood', 'Dark Wood'],
    sizes: null,
    features: ['Ultrasonic Technology', '7 LED Colors', 'Waterless Auto Shut-Off', '400ml Capacity'],
    createdAt: '2024-03-18T00:00:00Z'
  },

  // SPORTS (5)
  {
    id: 24,
    name: 'Yoga Mat Premium',
    description: 'Eco-friendly, non-slip yoga mat with perfect cushioning for joint support. Includes a carrying strap for easy transport.',
    price: 39.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/yoga-mat-premium-1/500/500', 'https://picsum.photos/seed/yoga-mat-premium-2/500/500', 'https://picsum.photos/seed/yoga-mat-premium-3/500/500'],
    category: 'Sports',
    categorySlug: 'sports',
    brand: 'ZenFit',
    rating: 4.7,
    reviewCount: 450,
    stock: 150,
    tags: ['fitness', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Purple', 'Teal', 'Black'],
    sizes: null,
    features: ['Eco-Friendly TPE Material', 'Non-Slip Surface', '6mm Thickness', 'Includes Carry Strap'],
    createdAt: '2024-01-08T00:00:00Z'
  },
  {
    id: 25,
    name: 'Smart Fitness Tracker',
    description: 'Slim and stylish fitness band that monitors heart rate, sleep quality, and daily activity. Water-resistant and features a 7-day battery life.',
    price: 49.99,
    originalPrice: 69.99,
    discount: 28,
    images: ['https://picsum.photos/seed/smart-fitness-tracker-1/500/500', 'https://picsum.photos/seed/smart-fitness-tracker-2/500/500', 'https://picsum.photos/seed/smart-fitness-tracker-3/500/500'],
    category: 'Sports',
    categorySlug: 'sports',
    brand: 'TechPro',
    rating: 4.4,
    reviewCount: 285,
    stock: 75,
    tags: ['tech', 'sale'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: ['Black', 'Pink', 'Blue'],
    sizes: null,
    features: ['Heart Rate Monitoring', 'Sleep Tracking', 'IP68 Waterproof', '7-Day Battery Life'],
    createdAt: '2024-02-14T00:00:00Z'
  },
  {
    id: 26,
    name: 'Adjustable Dumbbells',
    description: 'Space-saving adjustable dumbbell set ranging from 5 to 52.5 lbs per dumbbell. Perfect for home gyms and versatile strength training.',
    price: 349.00,
    originalPrice: 399.00,
    discount: 12,
    images: ['https://picsum.photos/seed/adjustable-dumbbells-1/500/500', 'https://picsum.photos/seed/adjustable-dumbbells-2/500/500', 'https://picsum.photos/seed/adjustable-dumbbells-3/500/500'],
    category: 'Sports',
    categorySlug: 'sports',
    brand: 'NovaSport',
    rating: 4.9,
    reviewCount: 160,
    stock: 20,
    tags: ['home-gym', 'featured'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Black/Red'],
    sizes: null,
    features: ['Adjusts from 5 to 52.5 lbs', 'Dial Mechanism', 'Space-Saving Design', 'Durable Molding'],
    createdAt: '2024-03-20T00:00:00Z'
  },
  {
    id: 27,
    name: 'Tennis Racket Pro',
    description: 'Professional-grade tennis racket offering an optimal blend of power and control. Lightweight graphite construction with comfortable grip.',
    price: 189.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/tennis-racket-pro-1/500/500', 'https://picsum.photos/seed/tennis-racket-pro-2/500/500', 'https://picsum.photos/seed/tennis-racket-pro-3/500/500'],
    category: 'Sports',
    categorySlug: 'sports',
    brand: 'CourtMaster',
    rating: 4.6,
    reviewCount: 92,
    stock: 45,
    tags: ['equipment'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Black/Yellow', 'White/Blue'],
    sizes: ['4 1/4', '4 3/8', '4 1/2'],
    features: ['Graphite Composition', '100 sq in Head Size', 'String Pattern 16x19', 'Pre-Strung'],
    createdAt: '2024-01-28T00:00:00Z'
  },
  {
    id: 28,
    name: 'Hiking Backpack 40L',
    description: 'Durable 40L hiking backpack with multiple compartments, rain cover, and breathable back panel. Ideal for day hikes and short camping trips.',
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    images: ['https://picsum.photos/seed/hiking-backpack-40l-1/500/500', 'https://picsum.photos/seed/hiking-backpack-40l-2/500/500', 'https://picsum.photos/seed/hiking-backpack-40l-3/500/500'],
    category: 'Sports',
    categorySlug: 'sports',
    brand: 'TrailBlazer',
    rating: 4.8,
    reviewCount: 134,
    stock: 60,
    tags: ['outdoor', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Green', 'Blue', 'Black'],
    sizes: null,
    features: ['40L Capacity', 'Included Rain Cover', 'Hydration Bladder Compatible', 'Breathable Mesh Back'],
    createdAt: '2024-02-10T00:00:00Z'
  },

  // BOOKS (5)
  {
    id: 29,
    name: 'The Art of Innovation',
    description: 'Discover the secrets to fostering creativity and driving innovation in business. A must-read for entrepreneurs and leaders.',
    price: 24.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/the-art-of-innovation-1/500/500', 'https://picsum.photos/seed/the-art-of-innovation-2/500/500', 'https://picsum.photos/seed/the-art-of-innovation-3/500/500'],
    category: 'Books',
    categorySlug: 'books',
    brand: 'Business Press',
    rating: 4.8,
    reviewCount: 540,
    stock: 120,
    tags: ['bestseller', 'business'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: ['Hardcover', 'Paperback', 'Kindle'],
    features: ['320 Pages', 'Published 2023', 'English Language', 'ISBN: 978-1234567890'],
    createdAt: '2023-11-15T00:00:00Z'
  },
  {
    id: 30,
    name: 'Mindful Leadership',
    description: 'A guide to leading with purpose, focus, and compassion in the modern workplace. Practical exercises and inspiring case studies.',
    price: 19.99,
    originalPrice: 28.00,
    discount: 28,
    images: ['https://picsum.photos/seed/mindful-leadership-1/500/500', 'https://picsum.photos/seed/mindful-leadership-2/500/500', 'https://picsum.photos/seed/mindful-leadership-3/500/500'],
    category: 'Books',
    categorySlug: 'books',
    brand: 'Mindful Publishing',
    rating: 4.6,
    reviewCount: 215,
    stock: 85,
    tags: ['leadership', 'sale'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: null,
    sizes: ['Hardcover', 'Paperback', 'Audiobook'],
    features: ['256 Pages', 'Published 2024', 'English Language', 'Includes Practical Exercises'],
    createdAt: '2024-03-01T00:00:00Z'
  },
  {
    id: 31,
    name: 'Digital Photography Guide',
    description: 'Comprehensive guide covering everything from camera basics to advanced editing techniques. Beautifully illustrated with examples.',
    price: 35.00,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/digital-photography-guide-1/500/500', 'https://picsum.photos/seed/digital-photography-guide-2/500/500', 'https://picsum.photos/seed/digital-photography-guide-3/500/500'],
    category: 'Books',
    categorySlug: 'books',
    brand: 'Visual Arts Press',
    rating: 4.9,
    reviewCount: 312,
    stock: 45,
    tags: ['education', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: ['Paperback'],
    features: ['400 Pages', 'Full Color Illustrations', 'Covers Adobe Lightroom', 'Beginner to Advanced'],
    createdAt: '2024-01-20T00:00:00Z'
  },
  {
    id: 32,
    name: 'Gourmet Cooking Masterclass',
    description: 'Over 100 exquisite recipes from world-renowned chefs, complete with step-by-step instructions and stunning food photography.',
    price: 45.00,
    originalPrice: 55.00,
    discount: 18,
    images: ['https://picsum.photos/seed/gourmet-cooking-masterclass-1/500/500', 'https://picsum.photos/seed/gourmet-cooking-masterclass-2/500/500', 'https://picsum.photos/seed/gourmet-cooking-masterclass-3/500/500'],
    category: 'Books',
    categorySlug: 'books',
    brand: 'Culinary Books',
    rating: 4.7,
    reviewCount: 189,
    stock: 30,
    tags: ['cooking'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: ['Hardcover'],
    features: ['350 Pages', '100+ Recipes', 'Premium Paper Quality', 'Stunning Photography'],
    createdAt: '2024-02-14T00:00:00Z'
  },
  {
    id: 33,
    name: 'Modern Architecture 2024',
    description: 'A visual journey through the most innovative and sustainable building designs of the year. A gorgeous coffee table book.',
    price: 65.00,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/modern-architecture-2024-1/500/500', 'https://picsum.photos/seed/modern-architecture-2024-2/500/500', 'https://picsum.photos/seed/modern-architecture-2024-3/500/500'],
    category: 'Books',
    categorySlug: 'books',
    brand: 'Design Media',
    rating: 4.5,
    reviewCount: 76,
    stock: 0,
    tags: ['art', 'design'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: ['Hardcover'],
    features: ['Large Format', 'Sustainable Design Focus', 'Interviews with Architects', 'High-Gloss Pages'],
    createdAt: '2024-04-10T00:00:00Z'
  },

  // TOYS & GAMES (4)
  {
    id: 34,
    name: 'Building Blocks Mega Set',
    description: 'Unleash creativity with this 1000-piece colorful building block set. Includes special pieces for building vehicles and buildings.',
    price: 49.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/building-blocks-mega-set-1/500/500', 'https://picsum.photos/seed/building-blocks-mega-set-2/500/500', 'https://picsum.photos/seed/building-blocks-mega-set-3/500/500'],
    category: 'Toys & Games',
    categorySlug: 'toys-games',
    brand: 'CreatePlay',
    rating: 4.8,
    reviewCount: 650,
    stock: 120,
    tags: ['kids', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['1000 Pieces', 'Includes Storage Box', 'Ages 4+', 'Compatible with Major Brands'],
    createdAt: '2023-12-05T00:00:00Z'
  },
  {
    id: 35,
    name: 'Remote Control Car Pro',
    description: 'High-speed RC car capable of reaching 30mph. Features 4WD, off-road tires, and a durable shock-proof chassis.',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    images: ['https://picsum.photos/seed/remote-control-car-pro-1/500/500', 'https://picsum.photos/seed/remote-control-car-pro-2/500/500', 'https://picsum.photos/seed/remote-control-car-pro-3/500/500'],
    category: 'Toys & Games',
    categorySlug: 'toys-games',
    brand: 'SpeedTech',
    rating: 4.6,
    reviewCount: 245,
    stock: 45,
    tags: ['hobbies', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: ['Red', 'Blue', 'Green'],
    sizes: null,
    features: ['Top Speed 30mph', '4-Wheel Drive', '2.4GHz Remote Control', 'Includes 2 Batteries'],
    createdAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 36,
    name: 'Strategy Board Game',
    description: 'Award-winning strategy board game for 2-4 players. Build your civilization, manage resources, and outsmart your opponents.',
    price: 39.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/strategy-board-game-1/500/500', 'https://picsum.photos/seed/strategy-board-game-2/500/500', 'https://picsum.photos/seed/strategy-board-game-3/500/500'],
    category: 'Toys & Games',
    categorySlug: 'toys-games',
    brand: 'TableTop Games',
    rating: 4.9,
    reviewCount: 890,
    stock: 200,
    tags: ['family', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['2-4 Players', '60-90 Min Playtime', 'Ages 10+', 'High Replayability'],
    createdAt: '2023-10-20T00:00:00Z'
  },
  {
    id: 37,
    name: 'Educational Tablet for Kids',
    description: 'Kid-safe learning tablet pre-loaded with educational games and books. Features parental controls and a durable bumper case.',
    price: 99.99,
    originalPrice: 129.99,
    discount: 23,
    images: ['https://picsum.photos/seed/educational-tablet-1/500/500', 'https://picsum.photos/seed/educational-tablet-2/500/500', 'https://picsum.photos/seed/educational-tablet-3/500/500'],
    category: 'Toys & Games',
    categorySlug: 'toys-games',
    brand: 'TechPro Kids',
    rating: 4.5,
    reviewCount: 312,
    stock: 80,
    tags: ['tech', 'education'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: ['Pink', 'Blue'],
    sizes: null,
    features: ['7" HD Display', 'Pre-loaded Content', 'Robust Parental Controls', 'Kid-Proof Case'],
    createdAt: '2024-03-05T00:00:00Z'
  },

  // GROCERIES (5)
  {
    id: 38,
    name: 'Organic Coffee Bundle',
    description: 'Set of 3 premium organic single-origin coffee roasts (Light, Medium, Dark). Sustainably sourced and freshly roasted.',
    price: 45.00,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/organic-coffee-bundle-1/500/500', 'https://picsum.photos/seed/organic-coffee-bundle-2/500/500', 'https://picsum.photos/seed/organic-coffee-bundle-3/500/500'],
    category: 'Groceries',
    categorySlug: 'groceries',
    brand: 'BeanRoasters',
    rating: 4.9,
    reviewCount: 420,
    stock: 150,
    tags: ['organic', 'bestseller'],
    isNew: false,
    isBestSeller: true,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: ['Whole Bean', 'Ground'],
    features: ['100% Organic Arabica', 'Fair Trade Certified', '3 x 12oz Bags', 'Freshly Roasted'],
    createdAt: '2024-01-10T00:00:00Z'
  },
  {
    id: 39,
    name: 'Premium Tea Collection',
    description: 'An elegant wooden box containing 40 artisanal tea pyramids. Features a selection of black, green, herbal, and oolong teas.',
    price: 35.00,
    originalPrice: 45.00,
    discount: 22,
    images: ['https://picsum.photos/seed/premium-tea-collection-1/500/500', 'https://picsum.photos/seed/premium-tea-collection-2/500/500', 'https://picsum.photos/seed/premium-tea-collection-3/500/500'],
    category: 'Groceries',
    categorySlug: 'groceries',
    brand: 'TeaLeaf & Co',
    rating: 4.7,
    reviewCount: 185,
    stock: 60,
    tags: ['gift'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 172800000).toISOString(),
    colors: null,
    sizes: null,
    features: ['40 Tea Pyramids', 'Wooden Presentation Box', 'Organic Ingredients', 'Hand-Blended'],
    createdAt: '2024-04-01T00:00:00Z'
  },
  {
    id: 40,
    name: 'Artisan Chocolate Box',
    description: 'A decadent 24-piece assortment of handcrafted Belgian chocolates. Includes truffles, caramels, and pralines.',
    price: 49.99,
    originalPrice: null,
    discount: null,
    images: ['https://picsum.photos/seed/artisan-chocolate-box-1/500/500', 'https://picsum.photos/seed/artisan-chocolate-box-2/500/500', 'https://picsum.photos/seed/artisan-chocolate-box-3/500/500'],
    category: 'Groceries',
    categorySlug: 'groceries',
    brand: 'CocoaCraft',
    rating: 4.8,
    reviewCount: 310,
    stock: 40,
    tags: ['premium', 'featured'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['24 Assorted Pieces', 'Premium Belgian Chocolate', 'Handcrafted', 'Elegant Gift Box'],
    createdAt: '2024-02-05T00:00:00Z'
  },
  {
    id: 41,
    name: 'Superfood Smoothie Kit',
    description: 'A month supply of organic superfood powders including spirulina, maca, and acai. Perfect for boosting your daily smoothies.',
    price: 55.00,
    originalPrice: 65.00,
    discount: 15,
    images: ['https://picsum.photos/seed/superfood-smoothie-kit-1/500/500', 'https://picsum.photos/seed/superfood-smoothie-kit-2/500/500', 'https://picsum.photos/seed/superfood-smoothie-kit-3/500/500'],
    category: 'Groceries',
    categorySlug: 'groceries',
    brand: 'PureHealth',
    rating: 4.6,
    reviewCount: 142,
    stock: 85,
    tags: ['health', 'organic'],
    isNew: false,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['3 x 8oz Pouches', 'USDA Organic', 'Non-GMO', 'Vegan & Gluten-Free'],
    createdAt: '2024-03-12T00:00:00Z'
  },
  {
    id: 42,
    name: 'Gourmet Spice Collection',
    description: 'Set of 12 premium, exotic spices from around the world. Comes in beautiful glass jars with a wooden spice rack.',
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    images: ['https://picsum.photos/seed/gourmet-spice-collection-1/500/500', 'https://picsum.photos/seed/gourmet-spice-collection-2/500/500', 'https://picsum.photos/seed/gourmet-spice-collection-3/500/500'],
    category: 'Groceries',
    categorySlug: 'groceries',
    brand: 'SpiceWorld',
    rating: 4.9,
    reviewCount: 220,
    stock: 0,
    tags: ['cooking', 'featured'],
    isNew: true,
    isBestSeller: false,
    isFlashSale: false,
    flashSaleEndsAt: null,
    colors: null,
    sizes: null,
    features: ['12 Exotic Spices', 'Glass Jars with Labels', 'Includes Wooden Rack', 'Freshly Ground'],
    createdAt: '2024-04-15T00:00:00Z'
  }
];

export const reviews = [
  { id: 1, productId: 1, userName: 'John Doe', userAvatar: 'https://picsum.photos/seed/JohnDoe/100/100', rating: 5, title: 'Amazing Sound Quality', comment: 'These headphones are incredible. The noise cancellation works perfectly on airplanes.', date: '2024-02-15T10:30:00Z', helpful: 24, verified: true },
  { id: 2, productId: 1, userName: 'Jane Smith', userAvatar: 'https://picsum.photos/seed/JaneSmith/100/100', rating: 4, title: 'Good but bulky', comment: 'Sound is great, but they feel a bit heavy after a few hours of wear.', date: '2024-03-01T14:20:00Z', helpful: 5, verified: true },
  { id: 3, productId: 2, userName: 'Mike Johnson', userAvatar: 'https://picsum.photos/seed/MikeJohnson/100/100', rating: 5, title: 'Perfect Smartwatch', comment: 'Tracks my workouts accurately and the battery lasts two days. Very satisfied.', date: '2024-03-10T09:15:00Z', helpful: 12, verified: true },
  { id: 4, productId: 3, userName: 'Sarah Lee', userAvatar: 'https://picsum.photos/seed/SarahLee/100/100', rating: 5, title: 'Stunning Video', comment: 'The 4K camera on this drone is mind-blowing. Very stable in light wind.', date: '2024-02-28T16:45:00Z', helpful: 30, verified: true },
  { id: 5, productId: 4, userName: 'David Clark', userAvatar: 'https://picsum.photos/seed/DavidClark/100/100', rating: 4, title: 'Loud and clear', comment: 'Great speaker for the beach. Bass is punchy.', date: '2024-04-05T11:20:00Z', helpful: 8, verified: true },
  { id: 6, productId: 8, userName: 'Alex Turner', userAvatar: 'https://picsum.photos/seed/AlexTurner/100/100', rating: 5, title: 'Classic style', comment: 'The leather feels premium and the fit is perfect. Highly recommend.', date: '2024-01-20T13:10:00Z', helpful: 15, verified: true },
  { id: 7, productId: 9, userName: 'Emma Watson', userAvatar: 'https://picsum.photos/seed/EmmaWatson/100/100', rating: 5, title: 'So comfortable', comment: 'Best running shoes I have ever owned. Like walking on clouds.', date: '2024-04-12T08:30:00Z', helpful: 42, verified: true },
  { id: 8, productId: 9, userName: 'Chris Evans', userAvatar: 'https://picsum.photos/seed/ChrisEvans/100/100', rating: 4, title: 'Great for jogging', comment: 'Very light, breathable, but the sizing runs slightly small.', date: '2024-04-15T10:00:00Z', helpful: 3, verified: false },
  { id: 9, productId: 11, userName: 'Sophia Grace', userAvatar: 'https://picsum.photos/seed/SophiaGrace/100/100', rating: 5, title: 'Beautiful dress', comment: 'Wore this to a gala and received so many compliments. High quality silk.', date: '2024-04-02T19:45:00Z', helpful: 18, verified: true },
  { id: 10, productId: 14, userName: 'Tom Hardy', userAvatar: 'https://picsum.photos/seed/TomHardy/100/100', rating: 5, title: 'Sets the mood', comment: 'Love the app integration. The colors are vibrant and easy to control.', date: '2024-03-22T21:10:00Z', helpful: 22, verified: true },
  { id: 11, productId: 15, userName: 'Lucy Liu', userAvatar: 'https://picsum.photos/seed/LucyLiu/100/100', rating: 5, title: 'Saved my back', comment: 'Working from home is much better now. Excellent lumbar support.', date: '2024-02-10T14:30:00Z', helpful: 50, verified: true },
  { id: 12, productId: 16, userName: 'Oliver Twist', userAvatar: 'https://picsum.photos/seed/OliverTwist/100/100', rating: 4, title: 'Very soft', comment: 'Super soft, but sheds a little bit at first. Fine after one wash.', date: '2024-02-25T17:20:00Z', helpful: 7, verified: true },
  { id: 13, productId: 19, userName: 'Mia Wallace', userAvatar: 'https://picsum.photos/seed/MiaWallace/100/100', rating: 5, title: 'Glowing skin', comment: 'I noticed a difference in a week. The serum is magical.', date: '2024-03-05T12:00:00Z', helpful: 35, verified: true },
  { id: 14, productId: 20, userName: 'Vincent Vega', userAvatar: 'https://picsum.photos/seed/VincentVega/100/100', rating: 4, title: 'Nice variety', comment: 'Great way to try different scents. The woody one is my favorite.', date: '2024-04-08T09:40:00Z', helpful: 11, verified: true },
  { id: 15, productId: 24, userName: 'Jackie Brown', userAvatar: 'https://picsum.photos/seed/JackieBrown/100/100', rating: 5, title: 'No slipping', comment: 'Finally a mat where my hands do not slide during hot yoga.', date: '2024-01-30T15:15:00Z', helpful: 28, verified: true },
  { id: 16, productId: 26, userName: 'Bruce Wayne', userAvatar: 'https://picsum.photos/seed/BruceWayne/100/100', rating: 5, title: 'Perfect for home gym', comment: 'Saves so much space and the mechanism is very smooth.', date: '2024-04-01T07:50:00Z', helpful: 45, verified: true },
  { id: 17, productId: 28, userName: 'Clark Kent', userAvatar: 'https://picsum.photos/seed/ClarkKent/100/100', rating: 5, title: 'Spacious and durable', comment: 'Took this on a 3-day hike. Held up great and was very comfortable.', date: '2024-03-12T20:30:00Z', helpful: 16, verified: true },
  { id: 18, productId: 29, userName: 'Diana Prince', userAvatar: 'https://picsum.photos/seed/DianaPrince/100/100', rating: 5, title: 'Inspiring read', comment: 'Full of great insights for my startup. Highly recommended.', date: '2023-12-10T11:00:00Z', helpful: 33, verified: true },
  { id: 19, productId: 32, userName: 'Barry Allen', userAvatar: 'https://picsum.photos/seed/BarryAllen/100/100', rating: 4, title: 'Great recipes', comment: 'Some recipes are a bit complex, but the results are delicious.', date: '2024-03-18T18:20:00Z', helpful: 9, verified: true },
  { id: 20, productId: 34, userName: 'Arthur Curry', userAvatar: 'https://picsum.photos/seed/ArthurCurry/100/100', rating: 5, title: 'Kids love it', comment: 'Keeps my kids entertained for hours. Lots of creative options.', date: '2024-01-05T13:45:00Z', helpful: 21, verified: true },
  { id: 21, productId: 35, userName: 'Victor Stone', userAvatar: 'https://picsum.photos/seed/VictorStone/100/100', rating: 4, title: 'Super fast', comment: 'Car is insanely fast. Battery life could be slightly better though.', date: '2024-02-02T16:10:00Z', helpful: 14, verified: true },
  { id: 22, productId: 36, userName: 'Hal Jordan', userAvatar: 'https://picsum.photos/seed/HalJordan/100/100', rating: 5, title: 'Best game night game', comment: 'Complex enough to be engaging, but easy enough to learn quickly.', date: '2023-11-20T19:30:00Z', helpful: 40, verified: true },
  { id: 23, productId: 38, userName: 'Wanda Maximoff', userAvatar: 'https://picsum.photos/seed/WandaMaximoff/100/100', rating: 5, title: 'Amazing flavor', comment: 'The dark roast is exceptionally smooth without being bitter.', date: '2024-02-15T08:00:00Z', helpful: 19, verified: true },
  { id: 24, productId: 40, userName: 'Natasha Romanoff', userAvatar: 'https://picsum.photos/seed/NatashaRomanoff/100/100', rating: 5, title: 'Decadent', comment: 'These chocolates melt in your mouth. The caramel ones are the best.', date: '2024-03-08T20:15:00Z', helpful: 27, verified: true },
  { id: 25, productId: 42, userName: 'Steve Rogers', userAvatar: 'https://picsum.photos/seed/SteveRogers/100/100', rating: 5, title: 'Fresh spices', comment: 'Elevated my cooking instantly. The presentation rack is a nice touch.', date: '2024-04-18T17:40:00Z', helpful: 31, verified: true },
  { id: 26, productId: 5, userName: 'Tony Stark', userAvatar: 'https://picsum.photos/seed/TonyStark/100/100', rating: 5, title: 'Clicky and responsive', comment: 'Switches feel great for gaming and typing alike.', date: '2024-04-10T22:15:00Z', helpful: 17, verified: true },
  { id: 27, productId: 7, userName: 'Peter Parker', userAvatar: 'https://picsum.photos/seed/PeterParker/100/100', rating: 4, title: 'Solid ANC', comment: 'ANC is very good for the price, fit is comfortable.', date: '2024-03-25T09:20:00Z', helpful: 10, verified: true },
  { id: 28, productId: 12, userName: 'Stephen Strange', userAvatar: 'https://picsum.photos/seed/StephenStrange/100/100', rating: 5, title: 'Luxurious feel', comment: 'Perfect cashmere sweater. Fits true to size and is so warm.', date: '2024-02-05T14:10:00Z', helpful: 23, verified: true },
  { id: 29, productId: 18, userName: 'Scott Lang', userAvatar: 'https://picsum.photos/seed/ScottLang/100/100', rating: 5, title: 'Saves so much time', comment: 'Maps the house perfectly and avoids obstacles.', date: '2024-02-28T11:45:00Z', helpful: 38, verified: true },
  { id: 30, productId: 22, userName: 'Carol Danvers', userAvatar: 'https://picsum.photos/seed/CarolDanvers/100/100', rating: 4, title: 'Bright lights', comment: 'Very bright and the magnification panels are super useful.', date: '2024-03-15T10:30:00Z', helpful: 12, verified: true },
  { id: 31, productId: 39, userName: 'Nick Fury', userAvatar: 'https://picsum.photos/seed/NickFury/100/100', rating: 5, title: 'Great gift', comment: 'Bought this as a gift and they loved the presentation and quality.', date: '2024-04-05T16:20:00Z', helpful: 8, verified: true }
];
